### ISSUE TITLE
react client 측 build가 필요한것 같습니다

### ISSUE THREAD

**Issue by kimdongjang** [sbjang123456/docker-fullstack#1]
순서대로 진행해봤는데 nginx에서 403 에러가 발생하더군요.
[error] 24#24: *1 directory index of "/usr/share/nginx/html/" is forbidden, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"

/usr/share/nginx/html에 가봤는데 올라간 페이지가 아무것도 없어서
react client를 빌드했더니 잘 작동합니다.

1. cd docker-fullstack/packages/client
2. npm update
3. npm run build
4. cd docker-fullstack
5. docker-compose build
6. docker-compose up -d

이 순서로 진행하면 잘 되는 것 같습니다

**Comment by sbjang123456** [comment]
감사합니다. 해당 내용 확인해보니, 구조상 프론트쪽 빌드를 먼저 진행 후 하는 것이 맞네요! 내용 추가하도록 하겠습니다.

**Comment by sbjang123456** [comment]
installation 에 해당내용 추가하였습니다. 감사합니다.
